# 特别说明：
#   1. 脚本定义使用代理模式，脚本内容通过 package.json scripts 字段定义
#   2. 默认构建输出目录为 `dist`，根据实际情况调整
#   3. 如果使用 `sentry` 监控，需要本地 `cli` 配置信息
stages:
  - build
  - test
  - deploy
  - monitor

compile:
  stage: build
  before_script:
    - yarn --ignore-engines
  script:
    - yarn run build
  cache:
    key: '$CI_PROJECT_ID'
    paths:
      - node_modules/
  artifacts:
    when: on_success
    expire_in: 15 mins
    paths:
      - dist/
  tags:
    - production
    - universal
    - wuxi

development:
  stage: deploy
  when: manual
  dependencies:
    - compile
  script:
    - yarn run tarball
    - yarn run deploy:development # 发布开发环境
  tags:
    - production
    - universal
    - wuxi

production:
  stage: deploy
  only:
    - master
    - tags
  dependencies:
    - compile
  script:
    - yarn run tarball # 静态内容合并压缩包
    - yarn run deploy:production # 发布生产环境
  when: manual
  tags:
    - production
    - universal
    - wuxi

sentry:
  stage: monitor
  only:
    - master
    - tags
  dependencies:
    - compile
  script:
    - yarn run sentry:setup # 安装 `@sentry/cli` 依赖
    - yarn run sentry:new # 新建 `release` 版本
    - yarn run sentry:sourcemaps # 上传构建 `sourcemaps`
  when: manual
  tags:
    - production
    - universal
    - wuxi
